version: "3.9"

services:
  redis:
    image: redis:7
    container_name: rwa_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: rwa_backend
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - UPLOAD_DRIVER=local
      - UPLOAD_LOCAL_PATH=/app/uploads
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: rwa_frontend
    command: npm start -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  redis_data: